name: musicwebapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  mini_music_visualizer: ^1.1.4
  responsive_builder: ^0.7.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
